name: Build and Push to Artifact Registry

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: prime-odyssey-428918-m1
  REGION: us-east1
  GAR_LOCATION: us-east1-docker.pkg.dev/prime-odyssey-428918-m1/repo1

jobs:
  build-push-artifact:
    permissions:
      contents: 'read'
      id-token: 'write'
      actions: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
            # credentials_json: "${{ secrets.GCP_SA_KEY }}"
            workload_identity_provider: 'projects/684049558896/locations/global/workloadIdentityPools/github-actions/providers/github'
            service_account: 'wif-github@prime-odyssey-428918-m1.iam.gserviceaccount.com'
            
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --tag ${{ env.GAR_LOCATION }}/nginx:latest

      # - name: Auth before push
      #   run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-east1-docker.pkg.dev
      - name: Pull image
        run: docker pull ${{ env.GAR_LOCATION }}/nginx:latest
